baseURL = 'http://nogo.wtf/'
languageCode = 'en-us'
title = "nogo's world"
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Nogo's world"
subtitle = "Web 3 is my life"
keywords = [ "Blog", "DeFi", "Ethereum", "Personal" ]
imageUrl = "pp.jpeg"
imageTitle = "nogo logo"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Articles"
url = "/posts"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Daily log"
url = "/logs"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/0xnogo"

[[params.socialIcons]]
name = "github"
url = "https://github.com/0xnogo"

[params.assets]
disableFingerprinting = true
favicon = "favicon/favicon.ico"
favicon16x16 = "favicon/favicon-16x16.png"
favicon32x32 = "favicon/favicon-32x32.png"
apple_touch_icon = "favicon/apple-touch-icon.png"
safari_pinned_tab = "favicon/safari-pinned-tab.svg"

[params.label]
text = "nogo's world"
icon = "pp.jpeg"
iconHeight = 35

[[menu.main]]
identifier = "posts"
name = "articles"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "project"
name = "projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "logs"
name = "logs"
url = "/logs"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]
