baseURL = 'http://nogo.wtf/'
languageCode = 'en-us'
title = "Nogo's world"
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Nogo's world"
subtitle = "Web 3 is my life"
imageUrl = "pp.jpeg"
imageTitle = "nogo logo"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Articles"
url = "/posts"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Daily log"
url = "/logs"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/0xnogo"

[[params.socialIcons]]
name = "github"
url = "https://github.com/0xnogo"

[assets]
disableFingerprinting = true
favicon = "favicon.ico"
favicon16x16 = "favicon.ico"
favicon32x32 = "favicon.ico"
apple_touch_icon = "favicon.ico"
safari_pinned_tab = "favicon.ico"

[[menu.main]]
identifier = "posts"
name = "articles"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "project"
name = "projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "logs"
name = "logs"
url = "/logs"
weight = 30
